### PR TITLE
[IO] Take strtod_l from stdlib.h if GLIBC >= 2.26

### LINKED ISSUE #1357: Fails to build: glibc 2.26 doesn't provide xlocale.h
silx 0.6.1 fails to build on Ubuntu 17.10 which includes glibc 2.26. glibc 2.26 no longer provides xlocale.h

You can see a build log at https://launchpad.net/ubuntu/+source/silx/0.6.1+dfsg-1. Click amd64.

Build log excerpt
-----------------------
silx/io/specfile/src/locale_management.c:27:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
          ^~~~~~~~~~~
compilation terminated.

### PR DESCRIPTION
**Pull request by vasole**
xlocale.h is removed in GLIBC 2.26 but strtod_l has been moved inside stdlib.h

closes #1357

### CODE REVIEW

**Comment by PiRK** [comment]
LGTM
