### ISSUE TITLE
Fails to build: glibc 2.26 doesn't provide xlocale.h

### ISSUE THREAD

**Issue by jbicha** [silx-kit/silx#1357]
silx 0.6.1 fails to build on Ubuntu 17.10 which includes glibc 2.26. glibc 2.26 no longer provides xlocale.h

You can see a build log at https://launchpad.net/ubuntu/+source/silx/0.6.1+dfsg-1. Click amd64.

Build log excerpt
-----------------------
silx/io/specfile/src/locale_management.c:27:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
          ^~~~~~~~~~~
compilation terminated.

**Comment by vasole** [comment]
The use of that include is triggered by an environment variable (SPECFILE_USE_GNU_SOURCE). It should be enough to get it undefined to have a successful (but not optimized) build.

**Comment by vasole** [comment]
We have to test glibc version used...

```
    Glibc 2.26 has dropped xlocale.h, but the functions needed (strtod_l()
    and strdof_l()) can be found in stdlib.h.
    Improve the detection method to allow newer builds to still make use of
    the locale-setting.
```

source: https://bugs.freedesktop.org/show_bug.cgi?id=102454

**Comment by vasole** [comment]
For reference purposes,  the defines we have to check in our code are found in https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html

In particular:

```
__GNUC__
__GNUC_MINOR__
__GNUC_PATCHLEVEL__

    These macros are defined by all GNU compilers that use the C preprocessor: C, C++, Objective-C and Fortran. Their values are the major version, minor version, and patch level of the compiler, as integer constants. For example, GCC version x.y.z defines __GNUC__ to x, __GNUC_MINOR__ to y, and __GNUC_PATCHLEVEL__ to z. These macros are also defined if you invoke the preprocessor directly.

    If all you need to know is whether or not your program is being compiled by GCC, or a non-GCC compiler that claims to accept the GNU C dialects, you can simply test __GNUC__. If you need to write code which depends on a specific version, you must be more careful. Each time the minor version is increased, the patch level is reset to zero; each time the major version is increased, the minor version and patch level are reset. If you wish to use the predefined macros directly in the conditional, you will need to write it like this:

    /* Test for GCC > 3.2.0 */
    #if __GNUC__ > 3 || \
        (__GNUC__ == 3 && (__GNUC_MINOR__ > 2 || \
                           (__GNUC_MINOR__ == 2 && \
                            __GNUC_PATCHLEVEL__ > 0))

    Another approach is to use the predefined macros to calculate a single number, then compare that against a threshold:

    #define GCC_VERSION (__GNUC__ * 10000 \
                         + __GNUC_MINOR__ * 100 \
                         + __GNUC_PATCHLEVEL__)
    …
    /* Test for GCC > 3.2.0 */
    #if GCC_VERSION > 30200

    Many people find this form easier to understand.
```

**Comment by vasole** [comment]
I do not have an Ubuntu 17.10 at hand, but it should be fixed by #1358. Do you have the possibility to check it at your side?

**Comment by jbicha** [comment]
Thanks, that commit fixes my issue.
