### PR TITLE
silx.io.specfile: Fixed `SpecFile` deallocation issue

### LINKED ISSUE #4128: tests failures against Pytest 8.2.0
As of **Pytest 8.2.0** (bisected to https://github.com/pytest-dev/pytest/pull/12096) `silx`' tests suite fails, for example:
```
(.run_venv) [builder@localhost python3-module-silx-2.1.0]$ python run_tests.py --installed -ra -Wignore --low-mem .run_venv/lib/python3/site-packages/silx/io/test/test_specfilewrapper.py::TestSpecfilewrapper::test_number_of_scans
================================ test session starts =================================
platform linux -- Python 3.12.2, pytest-8.2.0.dev25+g0dc036035, pluggy-1.5.0
rootdir: /usr/src/RPM/BUILD/python3-module-silx-2.1.0/.run_venv/lib/python3/site-packages/silx
configfile: ../../../../../pytest.ini
plugins: mock-3.14.0, xvfb-3.0.0
collected 1 item                                                                     

.run_venv/lib/python3/site-packages/silx/io/test/test_specfilewrapper.py .     [100%]

================================= 1 passed in 0.04s ==================================
AttributeError: 'Specfile' object has no attribute 'close'
Exception ignored in: 'silx.io.specfile.SpecFile.__dealloc__'
AttributeError: 'Specfile' object has no attribute 'close
```

Not sure if this is `silx` issue and anything can be done on its side.

### PR DESCRIPTION
**Pull request by t20100**
Checklist:

- [x] The PR title is formatted as: `<Module or Topic>: <Action> <Summary>` (see [contributing guidelines](https://github.com/silx-kit/silx/blob/main/CONTRIBUTING.rst#pull-request-title-format))

<hr>

Replaces the use of `__dealloc__` in `SpecFile` with `__del__` since the former should not call methods and the later is now supported (it was not with Python 2):

https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-methods-dealloc-and-del

> You need to be careful what you do in a `__dealloc__()` method. By the time your `__dealloc__()` method is called, the object may already have been partially destroyed and may not be in a valid state as far as Python is concerned, so you should avoid invoking any Python operations which might touch the object. In particular, don’t call any other methods of the object or do anything which might cause the object to be resurrected. It’s best if you stick to just deallocating C data.

closes #4128

### CODE REVIEW

**Comment by stanislavlevin** [comment]
I confirm that I can't see the reported problem with this fix.
Thank you!

**Comment by t20100** [comment]
Thanks for testing!
