### ISSUE TITLE
<class 'AttributeError'> 'ExternalLink' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by jpcbertoldo** [silx-kit/silx#3576]
**Disclaimer**: I apologize for the issue created in a hurry but I can provide more info/details as you require; I am at the ESRF until tomorrow (Thu 2021-12-16) in case you want to talk in person.

I have a collection of h5 files (anything from 10k up to 1M) which i group in folders of 10k, and I have a master file with external links pointing to each individual files (it has the same folder structure as the file system).

Here's the snnipet:

```Python
from h5py import File, ExternalLink
from silx.io.dictdump import dicttoh5

master_h5_filepath = parameters["output_filepath"]

with File(str(master_h5_filepath), "a") as h5f:
    
    h5f.require_group(f"/difspots")
    
    for filepath, difspot in zip(difspots_filepaths, difspots):
        
        h5f.require_group(f"/difspots/{filepath.parent.stem}")
        h5f[f"/difspots/{filepath.parent.stem}/{filepath.stem}"] = ExternalLink(filepath, "/")

del master_h5_filepath, File, ExternalLink, h5f, filepath, difspot, dicttoh5
```

In `silx view`, when I try to expand the level with the group of 10k links (so the level `h5f[f"/difspots/{filepath.parent.stem}]`), I get the following error (many times, so I guess it corresponds to the number of external links):

> <class 'AttributeError'> 'ExternalLink' object has no attribute 'attrs'
> Please report details

By clicking on "show details", I get: 

> 'ExternalLink' object has no attribute 'attrs'   File "/sware/isdd/packages/ubuntu20.04/dau/miniconda3/envs/dau/lib/python3.6/site-packages/silx/gui/hdf5/NexusSortFilterProxyModel.py", line 89, in lessThan File "/sware/isdd/packages/ubuntu20.04/dau/miniconda3/envs/dau/lib/python3.6/site-packages/silx/gui/hdf5/NexusSortFilterProxyModel.py", line 106, in __isNXentry

Opening the same file with `h5py` does not show any errors accessing any of the h5 groups in the levels mentioned

**Comment by t20100** [comment]
Related to #3537

This should be fixed in the latest version of `silx` v1.0.
Which version of `silx` do you use?
Let us know whether it works fine with 1.0 or not.

**Comment by t20100** [comment]
Closing, this should be fixed by #3545
Please reopen if needed
