### ISSUE TITLE
[silx view]Problem when reading a list of utf-8 strings

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2093]
I created a HDF5 file with a list of utf-8 strings, the following way (using Python2):

```
>>> import h5py
>>> text_dtype = h5py.special_dtype(vlen=unicode)
>>> import numpy
>>> def to_h5py_utf8(str_list):
...     """Convert a string or a list of strings to a numpy array of
...     unicode strings that can be written to HDF5 as utf-8.
...     """
...     return numpy.array(str_list, dtype=text_dtype)
... 
>>> f = h5py.File("toto.h5", "w")
>>> 
>>> f["spam"] = to_h5py_utf8(["foo", "bar"])
>>> f["ham"] = to_h5py_utf8([u"foo", u"bar"])
>>> 
>>> f.close()
```

When I open this file with `silx view` (current master) and I try to view one of the datasets, I get an error: 
```
ERROR:silx.gui.qt._qt:<type 'exceptions.AttributeError'> 'unicode' object has no attribute 'dtype'   File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/data/RecordTableView.py", line 209, in data
    return self.__formatter.toString(data, dtype=data.dtype)
```

The popup with the error message keeps poping up when I close it, so I have to kill `silx view`.

**Comment by PiRK** [comment]
With silx<=0.8.0 it works.

**Comment by PiRK** [comment]
Broken by https://github.com/silx-kit/silx/commit/fad4fde73262979a3d0e77f2d8545ad26d249374

I imagine the `RecordTableView` was not supposed to open basic arrays of unicode strings, but as they are stored as an array with a generic `dtype=object` it is not easy to guess that the objects are unicode.
