### ISSUE TITLE
[GUI] silx (view) does not work with PyQt6 with Qt 6.4.3

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#3776]
Released today. Many flags/enums in different namespaces.

A quick-and-dirty patch can be found at https://github.com/vasole/pymca/pull/972 but a cleaner solution is desirable

![image](https://user-images.githubusercontent.com/5636251/226388585-4931343f-4f1f-4ce2-acd6-3de52959e6db.png)

**Comment by t20100** [comment]
This is already taken care of by `silx.gui.qt`.

Tested with:
```
PyQt6                         6.4.2
PyQt6-Qt6                     6.4.3
PyQt6-sip                     13.4.0
```

```python
In [1]: import PyQt6.QtCore

In [2]: PyQt6.QtCore.Qt.Widget
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [2], line 1
----> 1 PyQt6.QtCore.Qt.Widget

AttributeError: type object 'Qt' has no attribute 'Widget'

In [3]: from silx.gui import qt

In [4]: qt.Qt.Widget
Out[4]: <WindowType.Widget: 0>

In [5]: PyQt6.QtCore.Qt.Widget
Out[5]: <WindowType.Widget: 0>
```

This is patched here:

https://github.com/silx-kit/silx/blob/77440ac5515073b7fa7c1ca8c3aa1856bb772ae8/src/silx/gui/qt/_qt.py#L240-L241
https://github.com/silx-kit/silx/blob/77440ac5515073b7fa7c1ca8c3aa1856bb772ae8/src/silx/gui/qt/_pyqt6.py#L41

I'm closing, please re-open if I missed something.
